# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='board',
            field=models.CharField(default='RNBQKBNRPPPPPPPPeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeepppppppprnbqkbnr', max_length=70),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
